version: "3.8"

services:
  fivem:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    tty: true
    stdin_open: true
    volumes:
      - ./server-data/cache:/opt/cfx-server/server-data/cache
      - ./server-data/config:/opt/cfx-server/server-data/config
      - ./server-data/crashes:/opt/cfx-server/server-data/crashes
      - ./server-data/resources:/opt/cfx-server/server-data/resources
      - ./entrypoint:/usr/bin/entrypoint
    ports:
      - "30120:30120"
      - "30120:30120/udp"
  db:
    image: mariadb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_DATABASE: usina
      MARIADB_USER: locos
      MARIADB_PASSWORD: locos@2022
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
